apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    service: flask
spec:
  selector:
    app: flask
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer # EC2&MinikubeはIngressに対応していないので外部に公開する
