apiVersion: v1
kind: Service
metadata:
  name: vue
  labels:
    service: vue
  name: vue
spec:
  selector:
    app: vue
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer #EC2&MinikubeはIngress使えないので外部公開はしない
